version: "3.8"

services:
  dps:
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - MG_LOG_LEVEL=ERROR
    hostname: dns.docker
    networks:
      dps:
        ipv4_address: 172.0.0.10
  localstack:
    hostname: localstack.docker
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    # network_mode: bridge
  postgres:
    hostname: postgres.docker
    image: postgres:16
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: jaasper
      POSTGRES_PASSWORD: jaasper
      POSTGRES_DB: jaasper
      LANG: 'C.UTF-8'
      LANGUAGE: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'
      LC_COLLATE: 'C.UTF-8'
      LC_CTYPE: 'C.UTF-8'
    tmpfs: /var/lib/postgresql/data
    # network_mode: bridge
    dns:
      - 172.0.0.10
    networks:
      - dps
networks:
  dps:
    ipam:
      config:
        - subnet: 172.0.0.0/24